# Generated by Django 3.1.4 on 2021-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='modulos',
            field=models.IntegerField(default=None),
        ),
    ]
